name: CI
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: ls
      - run: ./scripts/tests.sh
