name: CI
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Setup
        run: ./scripts/setup.sh
      - name: Tests
        run: ./scripts/tests.sh
  lint:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Setup
        run: ./scripts/setup.sh
      - name: Lint
        run: ./scripts/lint.sh
  build:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - uses: actions/checkout@v2
      - name: Setup
        run: ./scripts/setup.sh
      - name: Build
        run: ./scripts/build.sh
