name: CI
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Setup
        run: ./scripts/setup.sh
      - name: Tests
        run: ./scripts/tests.sh
  lint:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - name: Setup
        run: ./scripts/setup.sh
      - name: Lint
        run: ./scripts/lint.sh
