name: Workflow
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - run: |
          ls
      - run: |
          ./scripts/tests.sh
