name: CI
on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup project
        run: ./scripts/setup.sh
  tests:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - name: Run tests
        run: ./scripts/tests.sh
  lint:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - name: Lint
        run: ./scripts/lint.sh