name: CI
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: haxe:4.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up project
        run: ./scripts/setup.sh
      - name: Run tests
        run: ./scripts/tests.sh
      - name: Lint
        run: ./scripts/lint.sh