name: Publish Maven
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/checkout@v2

      - name: Publsih to git Maven
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: |
          make maven_publish