name: Publish PyPI
on: push

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3'
      - uses: actions/checkout@v2
      - name: Build
        run: ./scripts/build.sh
      - name: Install python deps
        run: python3 -m pip install wheel dumb-pypi
      - name: Build python package
        run: python3 setup.py bdist_wheel
      - name: Setup PyPI keys
        run: |
          # Load key from secret
          echo "${{ secrets.PYPI_DEPLOY_KEY }}" > ./pypi_ssh_key

          # Add ssh key
          ssh-add ./pypi_ssh_key

          # Remove key
          rm -f ./pypi_ssh_key
      - name: Publsih to git PyPI
        run: |
          git clone git@github.com:tales-pw/PyPI
          cd PyPI

          yes | cp ../dist/*.whl ./packages

          ls ./packages/*.whl > packages/packages.txt

          dumb-pypi \
            --package-list ./packages/packages.txt \
            --packages-url https://tales-pw.github.io/PyPI/packages/ \
            --output-dir .

          git add --all
          git config --local user.email "pypi@tales.pw"
          git config --local user.name "pypi"
          git commit -a -m "update"
          git push
