name: Publish PyPI
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3'
      - uses: actions/checkout@v2

      - name: Publsih to git PyPI
        env:
          PYPI_DEPLOY_KEY: ${{ secrets.PYPI_DEPLOY_KEY }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: make pypi_publish