name: Publish PyPI
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/setup-python@v2
        with:
          python-version: '3'
      - uses: actions/checkout@v2

      - name: Build
        run: ./scripts/build.sh

      - name: Install python deps
        run: python3 -m pip install wheel

      - name: Build python package
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: python3 setup.py bdist_wheel

      - name: Setup PyPI keys
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PYPI_DEPLOY_KEY }}"

      - name: Publsih to git PyPI
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git clone git@github.com:tales-pw/PyPI ./PyPI
          cd PyPI

          yes | cp ../dist/*.whl ./

          git add --all
          git config --local user.email "pypi@tales.pw"
          git config --local user.name "pypi"
          git commit -a -m "update"
          git push
